"""Surface brightness, rotation curves, dispersion, scale height."""

from .rotation import (
    BMAJ_ICO_ARCSEC,
    CALIBRATION_RT_ARCSEC,
    CALIBRATION_V0_KM_S,
    DISK_RADIUS_ARCSEC,
    DV_CHAN_NATIVE_KM_S,
    N_RINGS_MAX,
    N_RINGS_MIN,
    R0_MIN_OVER_BMAJ,
    V_K_MAX_KM_S,
    V_K_MIN_KM_S,
    aic_keep_stage_a,
    arctan_vc,
    curvature_penalty,
    monotonicity_penalty,
    omega_k,
    ring_regulariser,
    ring_vc,
    ring_velocity_bounds,
    rings_from_arctan,
    run_lambda_reg_campaign,
    select_lambda_reg,
    uniform_knot_radii,
)

__all__ = [
    "BMAJ_ICO_ARCSEC",
    "CALIBRATION_RT_ARCSEC",
    "CALIBRATION_V0_KM_S",
    "DISK_RADIUS_ARCSEC",
    "DV_CHAN_NATIVE_KM_S",
    "N_RINGS_MAX",
    "N_RINGS_MIN",
    "R0_MIN_OVER_BMAJ",
    "V_K_MAX_KM_S",
    "V_K_MIN_KM_S",
    "aic_keep_stage_a",
    "arctan_vc",
    "curvature_penalty",
    "monotonicity_penalty",
    "omega_k",
    "ring_regulariser",
    "ring_vc",
    "ring_velocity_bounds",
    "rings_from_arctan",
    "run_lambda_reg_campaign",
    "select_lambda_reg",
    "uniform_knot_radii",
]
